apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
spec:
  containers:
    - name: Redrose
      image: ubuntu:22.04.5
      ports:
        - containerPort: 80
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "200m"
          memory: "256Mi"
